from typing import Protocol, Any, TypeVar, List, Optional, Dict, Tuple
import numpy as np

PathNode = Tuple[float, float]
TrajNode = Tuple[float, float, float]

class RobotManagerProtocol(Protocol):
    """RobotManager 的接口定义"""
    def register_robot(self, robot: Any) -> None: ...
    def unregister_robot(self, robot: Any) -> None: ...
    def get_robot_state(self, robot_id: int) -> np.ndarray: ...
    def get_pred_states(self, robot_id: int) -> Optional[np.ndarray]: ...
    async def simulate_step(self, kt: int, config_mpc: Any, static_obstacles: Any) -> List[Any]: ...